packages:
  - name: alfred
  - name: iterm2
  - name: firefox
  - name: visual-studio-code
  - name: slack
  - name: docker
  # 文字がぼやける問題があるため、インストール後に問題があればアンインストールして手動で6.2系を入れ直す
  - name: libreoffice-language-pack
  - name: atok
  - name: inkdrop
  - name: rectangle # Magnetの代わり
